@startuml
skinparam linetype ortho
hide empty members

title __Global Gomoku UML__
together {
Package lab4.client {

    Class Listener {
        +Listener(client : GomokuClient, portnr : int)
        +closeSocket() : void
    }

    Class GomokuClient {
        +UNCONNECTED : static final int
        +SERVER : static final int
        +CLIENT : static final int
        +GomokuClient(portnr : int)
        +foundConnection(writer : Printwriter, reader : BufferedReader, amClient : boolean) : void
        +setGameState(gs : GameState) : void
        +sendMoveMessage(x : int, y : int) : boolean
        +sendNewGameMessage() : boolean
        +disconnect() : void
        +getConnectionStatus() : int
    }
}

Package lab4.data {

    Class GameGrid{
        +EMPTY : static final int
        +ME : static final int
        +OTHER : static final int
        +GameGrid(size : int)
        +getLocation(x : int, y : int) : int
        +getSize() : int
        +move(x : int, y : int, player : int) : boolean
        +clearGrid() : void
        +isWinner(player : int) : boolean
    }

    Class GomokuGameState {
        +GomokuGameState(gc : GomokuClient)
        +getMessageString() : String
        +getGameGrid() : GameGrid
        +move(x : int, y : int) : void
        +newgame() : void
        +recievedNewGame() : void
        +otherGuyLeft() : void
        +disconnect() : void
        +recievedMove(x : int, y : int)
    }
}

Package lab4.gui {

    Class ConnectionWindow {
        +ConnectionWindow(client : GomokuClient)
    }

    Class GomokuGUI {
        +GomokuGUI(gamestate : GomokuGameState, client : GomokuClient)
    }

    Class GamePanel {
        +GamePanel(grid : GameGrid)
        +getGridPosition(x : int, y : int) : int[]
    }
}

Package lab4 {

    Class GomokuMain {
        +main(String[] : argv) : void
    }
}
}
Class Runnable <<Interface>> {
    +run() : void
}

Class Observer <<Interface>> {
    +update(o : Observable, arg : Object)
}

Class ActionListener <<Interface>> {
    +actionPerformed(e : ActionEvent) : void
}

Class MouseListener <<Interface>> {
    +mouseClicked(e : MouseEvent) : void
    +mouseEntered(e : MouseEvent) : void
    +mouseExited(e : MouseEvent) : void
    +mousePressed(e : MouseEvent) : void
    +mouseReleased(e : MouseEvent) : void
}

Class JPanel {

}

Class Observable {

}

GomokuClient <.. GomokuGameState : observes
GomokuClient <.. GomokuGUI : observes
GameGrid <.. GamePanel : observes
GomokuGameState o-- GameGrid
GomokuGameState <.. GomokuGUI : observes
ConnectionWindow <.. GomokuGUI
GomokuGUI +-- ActionListener
GomokuGUI o-- GamePanel
GomokuGUI +-- MouseListener
GomokuMain o-- GomokuClient
GomokuMain o-- GomokuGUI
GomokuMain o-- GomokuGameState
Runnable <|.right. Listener
Runnable <|.. GomokuClient
ActionListener <|-- ConnectionWindow
Observer <|.up. GomokuGameState
Observer <|.up. GamePanel
Observer <|.up. GomokuGUI
JPanel <|-- GamePanel
Observable <|-up- GomokuClient
Observable <|-up- GameGrid
Observable <|-up- GomokuGameState

@enduml